languageCode: de-CH
languageName: Deutsch
weight: 10
title: Gian Luca Decurtins

params:
  displayName: Deutsch
  isoCode: de
  description: Hier erfährst du, wer ich bin und was ich mache.
  keywords:
    - Persönliche Webseite
    - Gian Luca Decurtins
    - Decurtins
    - Zürich
    - Zürich-Oerlikon
    - Oerlikon
    - 17
  author:
    image: img/kopf_hell.jpeg
    name: Gian Luca Decurtins
    headline: Zürich-Oerlikon
    links:
      - email: mailto:gian.luca.decurtins@pm.me
      - linkedin: https://linkedin.com/in/g17s/
      - strava: https://strava.com/athletes/g17s/
      - soundcloud: https://soundcloud.com/gianurban/
      - facebook: https://facebook.com/decurgia17/
      - github: https://github.com/gian-luca-decurtins/
