main:
  - name: About me
    pageRef: /about-me
    weight: 10
  - name: Projects
    pageRef: /projects
    weight: 20

footer:
  - name: Legal notice
    pageRef: /legal-notice
    weight: 10
  - name: Privacy statement
    pageRef: /privacy-statement
    weight: 20
